version:	"3.5"

services: 
  product:
    image: loja/product-api
    ports:
      - "8081:8081"
  
  user:
    image: loja/user-api
    ports:
      - "8080:8080"

  shopping:
    image: loja/shopping-api
    ports:
      - "8082:8082"

  gateway:
    image: loja/gateway
    ports:
      - "8084:8084"